
import bcrypt from 'bcryptjs';
const data = {
users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products : [

{
name : 'Free Shirt',
slug : 'free-shirt',
category : 'Shirts',
image : '/./images/shirt1.jpg',
price : 70,
brand : 'Nike',
rating : 4.5,
numReviews : 10,
countInStock : 20,
description : 'A popular shirt',
},
{
name : 'Fit Shirt',
slug : 'Fit-shirt',
category : 'Shirts',
image : '/./images/shirt2.jpg',
price : 70,
brand : 'Nike',
rating : 4.5,
numReviews : 10,
countInStock : 20,
description : 'A popular shirt',
},
{
name : 'Denim Shirt',
slug : 'Denim-Shirt',
category : 'Shirts',
image : '/./images/shirt3.jpg',
price : 70,
brand : 'Louis Vuitton',
rating : 4.5,
numReviews : 10,
countInStock : 20,
description : 'A popular shirt',
},
{
name : 'Packet Shirt',
slug : 'Packet-Shirt',
category : 'Shirts',
image : '/./images/shirt1.jpg',
price : 70,
brand : 'Emporio Armani',
rating : 4.5,
numReviews : 10,
countInStock : 20,
description : 'A popular shirt',
},
{
name : 'loosed Shirt',
slug : 'loosed-Shirt',
category : 'Shirts',
image : '/./images/shirt2.jpg',
price : 70,
brand : 'Gucci',
rating : 4.5,
numReviews : 10,
countInStock : 20,
description : 'A popular shirt',
},
{
name : 'Tight Shirt',
slug : 'Tight-Shirt',
category : 'Shirts',
image : '/./images/shirt3.jpg',
price : 70,
brand : 'D & G',
rating : 4.5,
numReviews : 10,
countInStock : 20,
description : 'A popular shirt',
},
  ],
}

export default data;